import duckdb
import polars as pl
from wood_ball.stats.nba_stats import NBA_Stats

# from wood_ball.library.static.icon_ref import icon_ref

stats = NBA_Stats()

# con = duckdb.connect('md:?motherduck_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImN3b29kMDEwN0BnbWFpbC5jb20iLCJzZXNzaW9uIjoiY3dvb2QwMTA3LmdtYWlsLmNvbSIsInBhdCI6IkhOVTBDdlBpdVh2VzJqeU80UnExV3RMUm1RN09FVTRybEowanhSV2ZMVDQiLCJ1c2VySWQiOiIwYTMzZGI5OC0xZGY1LTQxY2QtODRkOC0zZDAxNGU5NmFlZTUiLCJpc3MiOiJtZF9wYXQiLCJyZWFkT25seSI6ZmFsc2UsInRva2VuVHlwZSI6InJlYWRfd3JpdGUiLCJpYXQiOjE3MzUzOTkzMDN9.tK3gEbSK3Gpn5YtdIyqYd6ZNA2kMnU-re3Ew-RsgzQQ')
con = duckdb.connect('nba_data.duckdb')
# box_adv_player
con.execute("""
    CREATE TABLE nba_data.box_adv_player (
    GAME_ID STRING,
    TEAM_ID STRING,
    TEAM_ABBREVIATION STRING,
    TEAM_CITY STRING,
    PLAYER_ID STRING,
    PLAYER_NAME STRING,
    NICKNAME STRING,
    START_POSITION STRING,
    COMMENT STRING,
    MIN STRING,
    E_OFF_RATING DOUBLE,
    OFF_RATING DOUBLE,
    E_DEF_RATING DOUBLE,
    DEF_RATING DOUBLE,
    E_NET_RATING DOUBLE,
    NET_RATING DOUBLE,
    AST_PCT DOUBLE,
    AST_TOV DOUBLE,
    AST_RATIO DOUBLE,
    OREB_PCT DOUBLE,
    DREB_PCT DOUBLE,
    REB_PCT DOUBLE,
    TM_TOV_PCT DOUBLE,
    EFG_PCT DOUBLE,
    TS_PCT DOUBLE,
    USG_PCT DOUBLE,
    E_USG_PCT DOUBLE,
    E_PACE DOUBLE,
    PACE DOUBLE,
    PACE_PER40 DOUBLE,
    POSS BIGINT,
    PIE DOUBLE,
    PRIMARY KEY(GAME_ID, TEAM_ID, PLAYER_ID)
)
            """)

# box_adv_team
con.execute("""
    CREATE OR REPLACE TABLE nba_data.box_adv_team (
    GAME_ID STRING,
    TEAM_ID STRING,
    TEAM_NAME STRING,
    TEAM_ABBREVIATION STRING,
    TEAM_CITY STRING,
    MIN STRING,
    E_OFF_RATING DOUBLE,
    OFF_RATING DOUBLE,
    E_DEF_RATING DOUBLE,
    DEF_RATING DOUBLE,
    E_NET_RATING DOUBLE,
    NET_RATING DOUBLE,
    AST_PCT DOUBLE,
    AST_TOV DOUBLE,
    AST_RATIO DOUBLE,
    OREB_PCT DOUBLE,
    DREB_PCT DOUBLE,
    REB_PCT DOUBLE,
    E_TM_TOV_PCT DOUBLE,
    TM_TOV_PCT DOUBLE,
    EFG_PCT DOUBLE,
    TS_PCT DOUBLE,
    USG_PCT DOUBLE,
    E_USG_PCT DOUBLE,
    E_PACE DOUBLE,
    PACE DOUBLE,
    PACE_PER40 DOUBLE,
    POSS BIGINT,
    PIE DOUBLE,
    PRIMARY KEY(GAME_ID, TEAM_ID)
            )
            """)
# box trad player
con.execute("""
    CREATE OR REPLACE TABLE nba_data.box_trad_player (
    GAME_ID STRING,
    TEAM_ID STRING,
    TEAM_ABBREVIATION STRING,
    TEAM_CITY STRING,
    PLAYER_ID STRING,
    PLAYER_NAME STRING,
    NICKNAME STRING,
    START_POSITION STRING,
    COMMENT STRING,
    MIN STRING,
    FGM BIGINT,
    FGA BIGINT,
    FG_PCT DOUBLE,
    FG3M BIGINT,
    FG3A BIGINT,
    FG3_PCT DOUBLE,
    FTM BIGINT,
    FTA BIGINT,
    FT_PCT DOUBLE,
    OREB BIGINT,
    DREB BIGINT,
    REB BIGINT,
    AST BIGINT,
    STL BIGINT,
    BLK BIGINT,
    TOV BIGINT,
    PF BIGINT,
    PTS BIGINT,
    PLUS_MINUS DOUBLE,
    PRIMARY KEY(GAME_ID, TEAM_ID, PLAYER_ID)
    )
""")

# box trad team
con.execute("""
    CREATE OR REPLACE TABLE nba_data.box_trad_team (
    GAME_ID STRING,
    TEAM_ID STRING,
    TEAM_NAME STRING,
    TEAM_ABBREVIATION STRING,
    TEAM_CITY STRING,
    MIN STRING,
    FGM BIGINT,
    FGA BIGINT,
    FG_PCT DOUBLE,
    FG3M BIGINT,
    FG3A BIGINT,
    FG3_PCT DOUBLE,
    FTM BIGINT,
    FTA BIGINT,
    FT_PCT DOUBLE,
    OREB BIGINT,
    DREB BIGINT,
    REB BIGINT,
    AST BIGINT,
    STL BIGINT,
    BLK BIGINT,
    TOV BIGINT,
    PF BIGINT,
    PTS BIGINT,
    PLUS_MINUS DOUBLE,
    PRIMARY KEY(GAME_ID, TEAM_ID)
        )
            """)

# nba_game_log
con.execute("""
    CREATE OR REPLACE TABLE nba_data.nba_game_log (
    SEASON_ID STRING,
    TEAM_ID STRING,
    TEAM_ABBREVIATION STRING,
    TEAM_NAME STRING,
    GAME_ID STRING,
    GAME_DATE STRING,
    MATCHUP STRING,
    WL STRING,
    MIN BIGINT,
    FGM BIGINT,
    FGA BIGINT,
    FG_PCT DOUBLE,
    FG3M BIGINT,
    FG3A BIGINT,
    FG3_PCT DOUBLE,
    FTM BIGINT,
    FTA BIGINT,
    FT_PCT DOUBLE,
    OREB BIGINT,
    DREB BIGINT,
    REB BIGINT,
    AST BIGINT,
    STL BIGINT,
    BLK BIGINT,
    TOV BIGINT,
    PF BIGINT,
    PTS BIGINT,
    PLUS_MINUS BIGINT,
    VIDEO_AVAILABLE BIGINT,
    PRIMARY KEY(SEASON_ID, TEAM_ID, GAME_ID)
            )
            """)

con.close()